### ISSUE TITLE
After syncing with DropBox

### ISSUE THREAD

**Issue by jayeemsuh** [byhestia/springseed#99]
When trying to load the stock markup email I get this error: 

Uncaught node.js Error 
[Code]
TypeError: Cannot call method 'replace' of undefined
    at Lexer.lex (file:///tmp/.org.chromium.Chromium.qGl15M/public/application.js:13586:10)
    at Function.Lexer.lex (file:///tmp/.org.chromium.Chromium.qGl15M/public/application.js:13577:20)
    at marked (file:///tmp/.org.chromium.Chromium.qGl15M/public/application.js:14547:35)
    at eval (file:///tmp/.org.chromium.Chromium.qGl15M/public/application.js:10743:40)
    at IDBRequest.eval (file:///tmp/.org.chromium.Chromium.qGl15M/public/application.js:13124:24) [/CODE]

**Comment by penedeoro** [comment]
Hello, I am getting this error on the latest version of springseed.

~~~
Uncaught node.js Error 

TypeError: Cannot call method 'replace' of undefined
    at Lexer.lex (file:///tmp/.org.chromium.Chromium.61Dush/public/application.js:13586:10)
    at Function.Lexer.lex (file:///tmp/.org.chromium.Chromium.61Dush/public/application.js:13577:20)
    at marked (file:///tmp/.org.chromium.Chromium.61Dush/public/application.js:14547:35)
    at eval (file:///tmp/.org.chromium.Chromium.61Dush/public/application.js:10743:40)
    at IDBRequest.eval (file:///tmp/.org.chromium.Chromium.61Dush/public/application.js:13124:24)

~~~
